---
- hosts: localhost
  connection: local
  tasks:
    - name: Deploy Kubernetes Deployment manifest
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: spring-boot-k8s
          spec:
            selector:
              matchLabels:
                app: spring-boot-k8s
            replicas: 2 
            template:
              metadata:
                labels:
                  app: spring-boot-k8s
              spec:
                containers:
                  - name: spring-boot-k8s
                    image: docker.io/aesaganda/step1:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 9001 
