apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-k8s-ingress
spec:
  rules:
  - host: dreamgames.aestech.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: springboot-k8s-svc
            port:
              number: 9001